### ISSUE TITLE
Use GitHub Actions for CI

### ISSUE THREAD

**Issue by ronaldoussoren** [ronaldoussoren/altgraph#13]
- At least add automatic testing for the tip of the tree, consider adding testing of PRs as well.

- Investigate automatic releases to PyPI for tagged releases.

**Comment by hugovk** [comment]
* Please see PR #16 for the first bullet point. Will run for pushes and PRs.

* For the second, have a look at https://github.com/pypa/gh-action-pypi-publish. I've not had experience setting that up yet, but it shouldn't be too difficult and you can probably ping that repo's author for help if necessary.
