### ISSUE TITLE
0.17.1 and .2 releases not in repository

### ISSUE THREAD

**Issue by The-Compiler** [ronaldoussoren/altgraph#19]
It looks like there were recent [0.17.1](https://pypi.org/project/altgraph/0.17.1/) and [0.17.2](https://pypi.org/project/altgraph/0.17.2/) releases on PyPI, but the last push to this repository [was in February 2020](https://github.com/ronaldoussoren/altgraph/commits/master), thus missing the sources for those.

I first feared that someone gained access to your PyPI account, but after comparing the source releases, it looks like those were indeed intended :slightly_smiling_face:

**Comment by ronaldoussoren** [comment]
The repo should be up to date, I just pushed again and "git push --tags" didn't update any tags on GitHub.

Anyways, the releases were real. There will be a py2app update as well later this week, I'm working on some problems with Python 3.10 support.

**Comment by The-Compiler** [comment]
Thanks for the update! I'm guessing you pushed the tags but didn't push the `master` branch originally, but I can confirm it's up to date now.

It looks like 0.17.2 is missing from the [changelog](https://github.com/ronaldoussoren/altgraph/blob/master/doc/changelog.rst), however :slightly_smiling_face:

**Comment by ronaldoussoren** [comment]
I've pushed an update to the changelog. 0.17.2 only changes the setup.py file to fix broken PKG-INFO data that resulted in bad sidebar links on PyPI.

**Comment by The-Compiler** [comment]
Great, thanks again! 👍
